version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      args:
        BASE_IMAGE: "oraclelinux:8-slim"
    volumes:
      - ./database:/app/database
    environment:
      APP_NAME: icdgenie
      API_PORT: 9000
      APP_BASE_URL: http://localhost:8080/icdgenie
      DATABASE_PATH: /app/database/database.db
      LOG_FOLDER: logs
      LOG_LEVEL: debug
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
      args:
        BASE_IMAGE: "oraclelinux:8-slim"
        APP_PATH: /icdgenie
    environment:
      APP_PATH: /icdgenie
      API_BASE_URL: http://backend:9000
    links:
      - backend:backend
    ports:
      - "8080:80"
