version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    volumes:
      - ./database:/app/database
    env_file:
      - server/.env

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    environment:
      API_BASE_URL: http://backend:9000
    links:
      - backend:backend
    ports:
      - "8080:80"

  # On WSL:2, run the following commands to increase the max_map_count
  # wsl -d docker-desktop
  # sysctl -w vm.max_map_count=262144
  database:
    image: public.ecr.aws/opensearchproject/opensearch:latest
    environment:
      discovery.type: single-node
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SkyWalker2024!
    ports:
      - "9200:9200"
      - "9600:9600"
