version: "3"
services:
  icdgenie-database:
    build:
      context: .
      dockerfile: docker/database.dockerfile
      args:
        DATABASE_BASE_IMAGE: "oraclelinux:8-slim"
    volumes:
      - ./database/logs:/app/logs
    environment:
      APP_NAME: icdgenie
      API_PORT: 9000
      DATABASE_PATH: import/database.db
      LOG_FOLDER: logs
      LOG_LEVEL: debug
  icdgenie-frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    environment:
      APP_PATH: /icdgenie
      API_BASE_URL: http://icdgenie-database:9000
    links:
      - icdgenie-database:icdgenie-database
    ports:
      - "8080:80"
