version: "3"
services:
  database:
    build:
      context: .
      dockerfile: docker/database.dockerfile
      args:
        BASE_IMAGE: "oraclelinux:8-slim"
    volumes:
      - ./database/logs:/app/logs
    environment:
      APP_NAME: icdgenie
      API_PORT: 9000
      DATABASE_PATH: import/database.db
      LOG_FOLDER: logs
      LOG_LEVEL: debug
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
      args:
        BASE_IMAGE: "oraclelinux:8-slim"
        APP_PATH: /icdgenie
    environment:
      APP_PATH: /icdgenie
      API_BASE_URL: http://database:9000
    links:
      - database:database
    ports:
      - "8080:80"
